### ISSUE TITLE
Project ready but can't see presence

### ISSUE THREAD

**Issue by Saharsh1223** [Mewzax/Discord-RPC-Selfbot#12]
![Screenshot 2022-04-16 at 11 28 53 AM](https://user-images.githubusercontent.com/88390577/163663725-0d044f63-2b27-409f-bf3a-428e20d92be7.png)
![Screenshot 2022-04-16 at 11 29 14 AM](https://user-images.githubusercontent.com/88390577/163663733-ffbfa485-9b93-4a67-bfc6-8cf865a3b8e8.png)

Help

**Comment by Saharsh1223** [comment]
I followed all the steps mentioned

**Comment by Saharsh1223** [comment]
![Screenshot 2022-04-16 at 11 30 55 AM](https://user-images.githubusercontent.com/88390577/163663782-4367398b-b0af-4dd7-943f-0a980c1d71d3.png)

**Comment by Saharsh1223** [comment]
am i missing anything?

**Comment by Mewzax** [comment]
hummmmm, maybe you can't see your presence but others can see ? (try using a different account and seeing presence from your main to be sure)

**Comment by MrDarkShadoow** [comment]
> ![Screenshot 2022-04-16 at 11 30 55 AM](https://user-images.githubusercontent.com/88390577/163663782-4367398b-b0af-4dd7-943f-0a980c1d71d3.png)

"mode": "game",
"status": "online"

**Comment by Mewzax** [comment]
Lmfao i didnt see this part in his config lol
