### ISSUE TITLE
marche jamais

### ISSUE THREAD

**Issue by localsys** [Mewzax/Discord-RPC-Selfbot#17]
que ça soit en discord.js-selfbot v11 ou v13 le code marche pas, que ça soit en v11 ou v13 ça met la même erreur qui dit que mon token est invalide alors que j'ai un token valide

**Comment by Mewzax** [comment]
euh ça c a cause de ton token mais oui sinon le programme marche pas je vais bientot l update (y a un event qui est pas géré par la v11 et dcp ça plante au bout d un certain temps)

**Comment by localsys** [comment]
il a rien mon token, j'ai même essayé dme connecter avec mon token et ça a marché mdr c juste le truc qui bug jpense
