### ISSUE TITLE
Keep alive doesn't work

### ISSUE THREAD

**Issue by reynoldyehezkiel** [mewzax/Discord-RPC-Selfbot#19]
Whenever Discord is closed, it goes offline even Replit tab is still opened.

**Comment by mewzax** [comment]
even if u setup "status": "online" in config ?

**Comment by mewzax** [comment]
(sorry for closing but without error i don't see what can be the issue)

**Comment by reynoldyehezkiel** [comment]
yes, even "status": "online" in config.

**Comment by mewzax** [comment]
Is the rpc showed when you're in discord client ? Maybe you can use another program in same time : https://github.com/mewzax/discord-token-aliver

The aliver will keep you online and rpc selfbot will get you a custom presence

**Comment by reynoldyehezkiel** [comment]
Yes, the rpc is showed
