### ISSUE TITLE
Not an issue but..

### ISSUE THREAD

**Issue by hoemotion** [Mewzax/Discord-RPC-Selfbot#3]
Ayane > every other girl

**Comment by slowwdev** [comment]
> Ayane > every other girl

I agree 😏

**Comment by slowwdev** [comment]
> Ayane > every other girl

![Screenshot_20211213-222717_Chrome](https://user-images.githubusercontent.com/75091300/145891527-70f60464-cb44-4284-a596-d982bfbdce83.jpg)
I love your status man
